# Default values for platform-service
# Likely you will make a copy of this for your own platform service

# application name - required
app: 

version: v1
replicaCount: 1

# sample extra label, you can add as many as you want
#additionalPodLabels: |
#  saml-idp-forward-auth-filter: enabled

image:
  #registry and repository (no tag): platformteam.azurecr.io/myimage
  repository:
  # image tag (i.e. 105389)
  tag:
  pullPolicy: IfNotPresent
  # name of the pullSecret for the registry if used
  pullSecret:
  containerPort: 80

# Settings for creating default jwt AuthenticationPolicy
defaultJwtPolicy:
  # Only creates the policy if enabled - disable to create custom policy
  enabled: true
  # Supports a set of origins
  origins:
      # required
    - issuer: # "https://sts.windows.net/.../"
      # required
      jwksUri: "https://login.microsoftonline.com/common/discovery/keys"
      # recommended, but not requiring right now for backward compatibility
      audience: # Guid

service:
  # unspecified for default microservice (for now at least)
  type:
  # port number
  port: 80
  # provide access to other services
  liveness:
    enabled: false

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # Prefixes the service account with the release name
  useReleasePrefix: false
  # The name of the ServiceAccount to use (the actual service account name
  # will still be prefixed by the release prefix if that option is enabled.
  # If not set and create is true, a name is generated from the app
  name: 

gateway:
  # map virtual service to a gateway expose this service
  exposeService: true
  # gateway name (fully qualified if in a different namespace)
  name: gateway/one-gateway

defaultRouting:

  # Generate default virtual services and destination rules
  enabled: true

  # list of prefixes for route matching - overrides the default prefix (app)
  urlPrefixes:

  # catch-all route - anything not routed elsewhere will be routed here
  # When this is used, urlPrefixes are ignored (there should be only catch-all route for this host & gateway)
  catchAll: false

  # Redirect when a trailing slash is not included in the URL prefix
  # This is applied for each provided urlPrefix or the default prefix if none provided
  redirectOnNoTrailingSlash: true

  # options for rewriting the URL to remove the routing prefix before delivering
  # the request to the target pod
  rewriteUrlPrefix:
    # replace the routing prefix when enabled (when disabled, the URL is not adjusted)
    enabled: true
    # replace the routing prefix with the provided string
    # alternate prefixes should begin and end with a "/"
    # examples: "/", "/api/"
    replaceWith: "/"

  # route from all hosts (typically only common services)
  allHosts: false
  # hosts to take into account for routing rules (ignored if allHosts = true)
  hosts:
    - myhost.dnvgl.com

# Specify network and authorization policies
# Experimental - do not use outside of testing
accessPolicy:
  # Enable default network policy (set false and create your own if needed)
  # Experimental - do not use outside of testing
  networkPolicyEnabled: false
  # List of workloads allowed access to this workload
  # v1 - clean up this list to match what we really support
  appsAllowedAccess:
       # App identifier for workload
  #  - app1
  #  - app2
  #       # Service account name - use the default Specify service account name if you use a an alternate name
  #       alternateServiceAccountName:
  #       authorizedTo:
  #         - operation:
  #             methods: ["GET"]
  #             paths: ["/info"]


# Provide environment variable yaml
#environmentVariables:
#  - name: Serilog__MinimumLevel
#    value: Debug
#    valueFrom:
#      secretKeyRef:
#        name: mysecret
#        key: username

# Declare any volumes: name and mountPath are used for volumeMount at the container level
# volumeDefinition string underneath is copied verbatim into volumes
volumes:
#  - name: 
#    mountPath: 
#    volumeDefinition: |
#      azureFile:

# Resource requests and limits for primary container in pod
resources: {}
#  requests:
#    cpu: 250m
#    memory: 64Mi
#  limits:
#    cpu: 500m
#    memory: 128Mi

# Adjust resources requested for proxy sidecar (see https://istio.io/docs/concepts/performance-and-scalability/#cpu-and-memory)
proxyResources: {}
  # request values are passed to the envoy proxy through annotations
  # these may be set globally at the istio level, so only override by service if necessary
  # requests:
    # cpu: 10m
    # memory: 64Mi
  # limits are not currently supported

nodeSelector: {}

tolerations: []

affinity: {}
