# Default values for platform-site.
gateway: gateway/one-gateway
hosts:
- test-host.dnv.com

routes:
  - service: simple-route
    urlPrefixes:
      - service-prefix
    versions:
      - version: v1

  - service: alt-namespace
    namespace: alt-namespace
    urlPrefixes:
      - service-prefix
    versions:
      - version: v1

  - service:  alt-loadbalancer
    loadBalancerPolicy: ROUND_ROBIN
    versions:
      - version: v1
    urlPrefixes:
      - service-prefix

  - service: timeouts
    timeout: 4s
    urlPrefixes:
      - service-prefix
    versions:
      - version: v1
      - version: alt-timeout
        timeout: 5s

  - service: internal-only
    internalOnly: true
    urlPrefixes:
      - service-prefix
    versions:
      - version: v1

  - service: internal-except-version
    internalOnly: true
    urlPrefixes:
      - service-prefix
    versions:
      - version: v1
      - version: external
        internalOnly: false

  - service: internal-only-with-matches
    internalOnly: true
    urlPrefixes:
      - service-prefix
    versions:
      - version: v1
      - version: dev
        internalMatch:
          - uri:
              prefix: /service-prefix-dev/

  - service: service-no-retries
    urlPrefixes:
      - service-prefix
    retries:
      enabled: false
      settings:
        attempts: 4
    versions:
      - version: v1
      - version: with-retries
        retries:
          enabled: true
      - version: retry-attempts
        retries:
          enabled: true
          settings:
            attempts: 5
       
  - service: service-with-retries
    retries:
      enabled: true
      settings:
        attempts: 4
    urlPrefixes:
      - service-prefix
    versions:
      - version: no-retries
        retries:
          enabled: false
      - version: retry-attempts
        retries:
          settings:
            attempts: 5


  - service: service-no-redirect
    urlPrefixes:
      - service-prefix
    redirectOnNoTrailingSlash: false
    versions:
      - version: v1
      - version: dev
        urlPrefixes:
          - dev-override-prefix
      - version: exact-match-override
        exactPrefixMatch: true
        urlPrefixes:
          - dev-override-exact
      - version: version-with-redirect
        urlPrefixes:
          - service-prefix-nr
        redirectOnNoTrailingSlash: true

  - service: service-with-redirect
    urlPrefixes:
      - service-prefix
    redirectOnNoTrailingSlash: true
    versions:
      - version: v1
      - version: version-no-redirect
        urlPrefixes:
          - service-prefix-nr
        redirectOnNoTrailingSlash: false

  - service: service-no-rewrite
    urlPrefixes:
      - service-prefix
    rewriteUrlPrefix:
      enabled: false
    versions:
      - version: v1
      - version: dev
        urlPrefixes:
          - dev-override-prefix
      - version: exact-match-override
        exactPrefixMatch: true
        urlPrefixes:
          - dev-override-exact
      - version: with-rewrite
        rewriteUrlPrefix:
          enabled: true
      - version: with-alt-rewrite-url
        rewriteUrlPrefix:
          enabled: true
          replaceWith: "alt-prefix/"

  - service: service-alt-rewrite
    urlPrefixes:
      - service-prefix
    rewriteUrlPrefix:
      replaceWith: "alt-prefix/"
    versions:
      - version: v1
      - version: dev
        urlPrefixes:
          - dev-override-prefix
      - version: exact-match-override
        exactPrefixMatch: true
        urlPrefixes:
          - dev-override-exact
      - version: no-rewrite
        rewriteUrlPrefix:
          enabled: false
      - version: with-alt-rewrite-url
        rewriteUrlPrefix:
          replaceWith: "alt-prefix-v/"

  - service: multiple-prefixes
    urlPrefixes:
      - service-prefix-1
      - service-prefix-2
    versions:
      - version: v1
      - version: alt-prefies
        urlPrefixes:
          - version-prefix
      - version: exact-prefix
        exactPrefixMatch: true
        urlPrefixes:
        - version-prefix
