# Default values for platform-site.
gateway: gateway/one-gateway
hosts:
- test-host.dnv.com

routes:
  - service: simple-route
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
    versions:
      - version: v1

  - service: alt-namespace
    namespace: alt-namespace
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
    versions:
      - version: v1

  - service:  alt-loadbalancer
    loadBalancerPolicy: ROUND_ROBIN
    versions:
      - version: v1
    externalMatchConfig:
      urlPrefixes:
        - service-prefix

  - service: timeouts
    timeout: 4s
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
    versions:
      - version: v1
      - version: alt-timeout
        timeout: 5s

  - service: internal-only
    internalOnly: true
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
    versions:
      - version: v1

  - service: internal-except-version
    internalOnly: true
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
    versions:
      - version: v1
      - version: external
        internalOnly: false

  - service: service-no-retries
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
    retries:
      enabled: false
      settings:
        attempts: 4
    versions:
      - version: v1
      - version: with-retries
        retries:
          enabled: true
      - version: retry-attempts
        retries:
          enabled: true
          settings:
            attempts: 5
       
  - service: service-with-retries
    externalMatchConfig:
      retries:
        enabled: true
        settings:
          attempts: 4
      urlPrefixes:
        - service-prefix
    versions:
      - version: no-retries
        retries:
          enabled: false
      - version: retry-attempts
        retries:
          settings:
            attempts: 5


  - service: service-no-redirect
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
      redirectOnNoTrailingSlash: false
    versions:
      - version: v1
      - version: dev
        externalMatchConfig:
          urlPrefixes:
            - dev-override-prefix
      - version: exact-match-override
        externalMatchConfig:
          exactPrefixMatch: true
          urlPrefixes:
            - dev-override-exact
      - version: version-with-redirect
        externalMatchConfig:
          urlPrefixes:
            - service-prefix-nr
          redirectOnNoTrailingSlash: true

  - service: service-with-redirect
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
      redirectOnNoTrailingSlash: true
    versions:
      - version: v1
      - version: version-no-redirect
        externalMatchConfig:
          urlPrefixes:
            - service-prefix-nr
          redirectOnNoTrailingSlash: false

  - service: service-no-rewrite
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
      rewriteUrlPrefix:
        enabled: false
    versions:
      - version: v1
      - version: dev
        externalMatchConfig:
          urlPrefixes:
            - dev-override-prefix
      - version: exact-match-override
        externalMatchConfig:
          exactPrefixMatch: true
          urlPrefixes:
            - dev-override-exact
      - version: with-rewrite
        externalMatchConfig:
          rewriteUrlPrefix:
            enabled: true
      - version: with-alt-rewrite-url
        externalMatchConfig:
          rewriteUrlPrefix:
            enabled: true
            replaceWith: "alt-prefix/"

  - service: service-alt-rewrite
    externalMatchConfig:
      urlPrefixes:
        - service-prefix
      rewriteUrlPrefix:
        replaceWith: "alt-prefix/"
    versions:
      - version: v1
      - version: dev
        externalMatchConfig:
          urlPrefixes:
            - dev-override-prefix
      - version: exact-match-override
        externalMatchConfig:
          exactPrefixMatch: true
          urlPrefixes:
            - dev-override-exact
      - version: no-rewrite
        externalMatchConfig:
          rewriteUrlPrefix:
            enabled: false
      - version: with-alt-rewrite-url
        externalMatchConfig:
          rewriteUrlPrefix:
            replaceWith: "alt-prefix-v/"

  - service: multiple-prefixes
    externalMatchConfig:
      urlPrefixes:
        - service-prefix-1
        - service-prefix-2
    versions:
      - version: v1
      - version: alt-prefies
        externalMatchConfig:
          urlPrefixes:
            - version-prefix
      - version: exact-prefix
        externalMatchConfig:
          exactPrefixMatch: true
          urlPrefixes:
          - version-prefix
