{{- if .Values.accessPolicy.authorizationPolicyEnabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Release.Namespace }}
 spec:
 action: ALLOW
 rules:
{{- range .Values.accessPolicy.authorizedServices }}
 - from:
   - source:
     principals: [{{ required "servicePrincipal is required" .servicePrincipal }}]
{{- if ( .requireJwt | default true ) }}
     requestPrincipals: ["*"]
{{- end }}
{{- end }}
{{- end }}
