{{- if not .Values.deploymentOnly -}}
{{- if .Values.defaultJwtPolicy.enabled -}}
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ include "platform-service.name" . }}-jwt-policy
spec:
  targets:
  - name: {{ include "platform-service.name" . }}
  peers:
  - mtls: {}
  origins:
  {{- range .Values.defaultJwtPolicy.origins }}
  - jwt:
      issuer: {{ required "issuer is required" .issuer }}
      jwksUri: {{ required "jkwsUri is required" .jwksUri }}
      audience: {{ .audience }}
 {{- end }}
  principalBinding: USE_ORIGIN
{{- end }}
{{- end }}
