{{- if .Values.defaultNetworkIsolation.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app }}-network-policy
  namespace: {{ .Release.Namepsace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  policyTypes:
    - Ingress
  ingress:
{{- range .Values.defaultNetworkIsolation.appsAllowedAccess }}
  - from:
    - podSelector:
        matchLabels:
          app: {{ . }}
    ports:
    - protocol: TCP
      port: {{ $.Values.image.containerPort }}
{{- end }}      
{{- end }}      
