{{- if .Values.accessPolicy.networkPolicyEnabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  policyTypes:
    - Ingress
  ingress:
{{- range .Values.accessPolicy.appsAllowedAccess }}
  - from:
    - podSelector:
        matchLabels:
          app: {{ . }}
    ports:
    - protocol: TCP
      port: {{ $.Values.image.containerPort }}
{{- end }}      
{{- range .Values.accessPolicy.appsAllowedAccess }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ . }}-egress-to-{{ $.Values.app }}-network-policy
  namespace: {{ $.Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ . }}
  policyTypes:
    - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ $.Values.app }}
          version: {{ $.Values.version }}
{{- end }}      
{{- end }}      
