{{- if .Values.accessPolicy.enablePeerAuthentication }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
{{- end }}
