{{- /* disabling peer authentication is not meant to be exposed to values.yaml */ -}}
{{- /* workaround for default value not working with bool */ -}}
{{- if or (.Values.enablePeerAuthentication) (eq (.Values.enablePeerAuthentication | toString) "<nil>") }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
{{- end }}
