{{- if .Values.accessPolicy.requestAuthentication.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: {{ .Values.app }}
 namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  jwtRules:
{{ .Values.accessPolicy.requestAuthentication.jwtRules | toYaml | indent 2 }}
{{- end }}