{{- if .Values.accessPolicy.jwtPolicy.origins -}}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: {{ .Values.app }}
 namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  jwtRules:
{{- range .Values.accessPolicy.jwtPolicy.origins }}
  - issuer: {{ required "issuer is required" .issuer  | quote }}
    jwksUri: {{ required "jkwsUri is required" .jwksUri  | quote }}
    audiences: [{{ .audience | quote }}]
{{- end }}
{{- end }}
