{{- if not .Values.deploymentOnly -}}
{{- if .Values.defaultRouting.enabled}}
{{- $fullName := include "platform-service.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "platform-service.serviceName" . }}
spec:
  hosts:
  - {{ include "platform-service.serviceName" . }}

  http:
  - route:
    - destination:
        host: {{ include "platform-service.serviceName" . | quote }}
    retries:
      attempts: 3
      perTryTimeout: 2s

{{- if .Values.gateway.exposeService }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "platform-service.serviceName" . }}-external
spec:
  hosts:
{{- if .Values.defaultRouting.allHosts }}
  - "*"
{{- else }}
  {{- range .Values.defaultRouting.hosts }}
  - {{ . | quote }}
  {{- end }}
{{- end }}
  gateways:
  - {{ required "A valid .Values.gateway.name entry required!" .Values.gateway.name }}
{{- $prefixes := default (list .Values.app) .Values.defaultRouting.urlPrefixes }}
  http:
{{- if .Values.defaultRouting.redirectOnNoTrailingSlash }}
  # redirect on prefixes without trailing slashes
  {{- range $prefixes }}
  {{- $slashPrefix := printf "/%s" . }}
  - match:
    - uri:
        exact: {{ $slashPrefix }}
    redirect:
      uri: {{ $slashPrefix }}/
  {{- end}}
{{- end}}
  # routes to service
  - route:
    - destination:
        host: {{ include "platform-service.serviceName" . | quote }}
  {{- if not .Values.defaultRouting.catchAll }}
    match:
    {{- range $prefixes }}
    {{- if hasPrefix "/" . }}
      {{ fail "url prefixes must not include leading slash"}}
    {{- end}}
    {{- $slashPrefix := printf "/%s" . }}
    - uri:
        prefix: {{ $slashPrefix }}/
    {{- end }}
  {{- end }}
{{- if .Values.defaultRouting.rewriteUrl }}
    # legacy rewrite
    rewrite:
      uri: "/"
{{- else if .Values.defaultRouting.enableRewrite }}
    rewrite:
      uri: {{ required "rewriteUri is required" .Values.defaultRouting.rewriteUri }}
{{- end}}
    headers:
      request:
        add:
          x-appname: {{ first $prefixes }}
    retries:
      attempts: 3
      perTryTimeout: 2s
{{- end}}
{{- end}}
{{- end}}
