platform-service:
  app: httpbin
  version: v1

  image:
    registry: docker.io
    repository: kennethreitz/httpbin
    pullPolicy: IfNotPresent
    tag: latest
    containerPort: 80

  service:
    port: 8000

  gateway:
    exposeService: true

  defaultJwtPolicy:
    enabled: false
    origins:
      - issuer: "https://login.microsoftonline.com/a68572e3-63ce-4bc1-acdc-b64943502e9d/v2.0/"
        jwksUri: "https://login.microsoftonline.com/te/dnvglb2cprod.onmicrosoft.com/b2c_1a_signinwithadfsidp/discovery/v2.0/keys"
        audience: "guid"

  defaultRouting:
    allHosts: true

  environmentVariables:
    - name: var1
      value: abc
    - name: "var2"
      value: "def"
    - name: database__usessl
      value: "false"
    - name: database__provider
      value: postgres
    - name: database__server
      valueFrom:
        secretKeyRef:
          name: plant-storage-postgres-secret
          key: PG_SERVER
    - name: database__databasename
      valueFrom:
        secretKeyRef:
          name: plant-storage-postgres-secret
          key: PG_DB
    - name: database__username
      valueFrom:
        secretKeyRef:
          name: plant-storage-postgres-secret
          key: PG_USER
    - name: database__password
      valueFrom:
        secretKeyRef:
          name: plant-storage-postgres-secret
          key: POSTGRES_PASSWORD

  volumes:
    - name: asset-registry-eventstore-volume
      mountPath: "/credentials/asset-registry-eventstore"
      volumeDefinition: |
        secret:
          secretName: asset-registry-eventstore-secrets
    - name: asset-registry-viewcache-volume
      mountPath: "/credentials/asset-registry-viewcache"
      volumeDefinition: |
        secret:
          secretName: asset-registry-viewcache-secrets
    - name: service-secrets
      mountPath: "/secrets"
      volumeDefinition: |
        secret:
          secretName: cascade-secrets
        

  # Specify network and authorization policies
  accessPolicy:
    # Enable default network policy (set false and create your own if needed)
    networkPolicyEnabled: true
    # List of workloads allowed access to this workload
    appsAllowedAccess:
      # App identifier for workload
      - sleep
