# Default values for platform-site.

gateway: gateway/one-gateway
hosts:
- cascade-devtest.dnv.com
session-management:
  enabled: true
  # namespace:  default is release
  

routes:
  # cascade.efficientenergy.com/assets
  - service: asset-registry-svc
    namespace: cascade
    versions:
      - version: v2
        urlPrefix: cas-mobile-svc
      - version: dev
        urlPrefix: devcas-mobile-svc
        add: 
          x-version: dev
    timeout: 10s
    externalMatchConfig:
      urlPrefixes:
      - assets

  # cascade-uat.efficientenergy.com/assets
  - service: asset-registry-svc
    namespace: cascade-uat
    versions:
      - version: v1
    timeout: 10s
    externalMatchConfig:
      urlPrefixes:
      - assets



  - service: internal
    namespace: ns
    versions:
      - version: v1
    internalOnly: true
    timeout: 10s

  - service: my-app
    versions:
      - version: v1
    externalMatchConfig:
      urlPrefixes:
      - prefix1
      - prefix2
      rewriteUrlPrefix:
        enabled: false
        replaceWith: "blah"

  - service:  my-app
    versions:
      - version: v1
    externalMatchConfig:
      urlExactMatches:
        - test-exact
    loadBalancerPolicy: ROUND_ROBIN #RANDOM

  - service:  my-app
    versions:
      - version: v1
    externalMatchConfig:
      catchAll: true
      retries:
        enabled: true
    corsPolicy:

