# Default values for platform-site.
gateway: gateway/one-gateway
hosts:
- cascade-devtest.dnv.com
session-management:
  enabled: true
  # namespace:  default is release

defaults:
  timeout: 3s
  retries:
    enabled: true
    settings:
      attempts: 3
  redirectOnNoTrailingSlash: true
  exactPrefixMatch: false
  rewriteUrlPrefix:
    enabled: true
    replaceWith: "/"
  loadBalancerPolicy: RANDOM
  internalOnly: false

routes: []