# Default values for platform-site.
gateway: gateway/one-gateway
hosts:
- cascade-devtest.dnv.com
session-management:
  enabled: true
  # namespace:  default is release

defaults:
  timeout: 3s
  retries:
    enabled: true
    settings:
      attempts: 3
  externalMatchConfig:
    redirectOnNoTrailingSlash: true
    exactPrefixMatch: false
    rewriteUrlPrefix:
      enabled: false
      replaceWith: "/"
  loadBalancerPolicy: RANDOM
  internalOnly: false

routes: []