{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ required "app is required" .Values.app }}
  name: {{ include "platform-service.fullname" . }}-hpa
spec:
  maxReplicas: {{.Values.hpa.maxReplicas}}
  minReplicas: {{.Values.hpa.minReplicas}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "platform-service.fullname" . }}
  targetCPUUtilizationPercentage: 80
{{- end }}
