{{- if .Values.image.fluxAutomation.enabled -}}
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: {{ include "platform-service.name" . }}
spec:
  imageRepositoryRef:
    name: {{ include "platform-service.name" . }}
{{- if .Values.image.fluxAutomation.filterTags }}
{{ .Values.image.fluxAutomation.filterTags | toYaml | nindent 2 }}
{{- end }}
{{ (required "policy is required when fluxAutomation is enabled" .Values.image.fluxAutomation.policy) | toYaml | nindent 2 }}
{{- end }}
